### ISSUE TITLE
Permanlinks dont work for Jekyll

### ISSUE THREAD

**Issue by clintonshanewright** [puma/puma.io#21]
Hi,

I am trying to use Puma as my webserver for my jekyll site and it works except that my jekyll permanlinks for my pages dont work.

If I serve my site using `jekyll serve` my permanlinks works as expected, but when I use puma they dont work.

Example of the feature not working. I have the following permalink in my yaml front matter for an introduction.md page located in the root directory:

    ---
    layout: default
    title: Introduction
    permanlink: /introduction
    ---

I tried to look at puma's help and didnt see anything about the permanlinks.

Any help is appreciated.

**Comment by nateberkopec** [comment]
Hi, you should open this issue at the jekyll repository.

**Comment by clintonshanewright** [comment]
Hi not so, this problem occurs for me only when running jekyll with the puma server. When I use the standard engine I dont experience this problem. So the problem is specific to puma server.

**Comment by sorsaffari** [comment]
@clintonshanewright  did you happen to solve this problem? I'm experiencing the same issue.

@nateberkopec just to clarify, I believe what @clintonshanewright is pointing out here is that, for instance, when the url ends with `/introduction.html` the content is displayed correctly, whereas when it only ends with `/introduction`, the file isn't found by puma. This is in contrast with what's explained in [Jekyll's docs on permalinks](https://jekyllrb.com/docs/permalinks/#extensionless-permalinks) as the expected behaviour.

It's also worth pointing out that, in my case, this broke right after replacing WEBrick with Puma.
